apiVersion: apps/v1
kind: Deployment
metadata:
  name: cds122512-helm-{{ .Release.Name }}
  labels:
    app: cds122512-helm
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: cds122512-helm
  template:
    metadata:
      labels:
        app: cds122512-helm
    spec:
      containers:
        - name: app
          image: {{ .Values.image }}
          ports:
            - containerPort: {{ .Values.containerPort }}
          readinessProbe:
            tcpSocket:
              port: {{ .Values.containerPort }}
            initialDelaySeconds: {{ .Values.readinessInitialDelaySeconds }}
            periodSeconds: 3
