pipeline:
  stages:
  - name: Stage
    id: stage
    steps:
    - id: check_ws
      run:
        shell: sh
        script: |-
          echo "HARNESS_WORKSPACE=[$HARNESS_WORKSPACE]"
          echo "PWD=$(pwd)"
    runtime: shell
    timeout: 10m
