pipeline:
  stages:
  - name: ServiceOnly
    id: serviceonly
    service: sls_s3_s3_enma
    steps:
    - id: check_ws
      run:
        shell: sh
        script: |-
          echo "HARNESS_WORKSPACE=[$HARNESS_WORKSPACE]"
          echo "PWD=$(pwd)"
    runtime: shell
    timeout: 10m
  - name: EnvironmentOnly
    id: environmentonly
    environment:
      id: ServerlessEnv_tNg4N
      deploy-to: infra_deBLD
    steps:
    - id: check_ws
      run:
        shell: sh
        script: |-
          echo "HARNESS_WORKSPACE=[$HARNESS_WORKSPACE]"
          echo "PWD=$(pwd)"
    runtime: shell
    timeout: 10m
