pipeline:
  stages:
  - name: Stage
    id: stage
    service: sls_s3_s3_enma
    environment:
      id: ServerlessEnv_tNg4N
      deploy-to: infra_deBLD
    steps:
    - id: check_ws
      run:
        container:
          image: library/alpine
          connector: account.harnessImage
        shell: sh
        script: |-
          echo "HARNESS_WORKSPACE=[$HARNESS_WORKSPACE]"
          echo "PWD=$(pwd)"
    - name: Package
      id: packagestep
      template:
        uses: serverlessPackageStep
        with:
          pre_exec_cmd: cd "$(echo ${PLUGIN_SERVERLESS_FILE_PATH} | tr -d '"' | sed
            's:/*$::')" && npm install
          image: harnessdev/serverless-plugin:0.0.2-nodejs24.x-1.151.0
          container_registry: account.harnessImage
    - name: Deploy
      id: deploystep
      template:
        uses: serverlessDeployStep
        with:
          pre_exec_cmd: cd "$(echo ${PLUGIN_SERVERLESS_FILE_PATH} | tr -d '"' | sed
            's:/*$::')" && npm install
          image: harnessdev/serverless-plugin:0.0.2-nodejs24.x-1.151.0
          container_registry: account.harnessImage
    runtime:
      kubernetes:
        namespace: default
        connector: connector_K8sCluster_local
    timeout: 10m
