

pipeline:
  stages:
    - steps:
        - name: jira_approval
          id: jira_approval
          deploy:
            uses: jiraApproval@1.0.8
            with:
              connector: jira_local
              issue: CDS-129988
              approve:
                match-any-condition: false
                conditions:
                  - Status:
                      eq: Done
              log_level: info
              reject:
                match-any-condition: true
                conditions:
                  - Status:
                      eq: Rejected
      runtime:
        kubernetes:
          namespace: default
          connector: account.KubernetesConnectorForAutomationTest
